;Implement a function to find a value in a list and replace it with a new value.
;
;(: findAndReplace (-> $oldValue $newValue $list $modifiedList))

;Implement a function to find and remove a value from a list.
;
;(: findAndRemove (-> $value $list $modifiedList))

;Implement a sort function that sorts a list of numbers and returns a sorted list.
;
;(: sort (-> $list $sortedList))

;Implement max and min functions that find the maximum and minimum values in a list, respectively.

