;`Key-Value Store`
;leverage the idea of non-determinism to implement a key-value store datastructure
;where you can store different types of values and query them with a specified key.
;NOTE: avoid key collisions while attempting to implement the key-value store.
;
;functions to implement:
;(: addValue (-> $key $value (->)))
;(: getAt (-> $key $value))

;`superpose`
;use superpose to implement the `map` function.
;
;(: map (-> $function $list Expression))
